Resources:
  estadisticasClimaticas:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: estadisticas-climaticas
      AttributeDefinitions:
        - AttributeName: uuid
          AttributeType: S
        - AttributeName: estacion
          AttributeType: S  
        - AttributeName: temp
          AttributeType: S
        - AttributeName: tempMax
          AttributeType: S  
        - AttributeName: tempMin
          AttributeType: S
        - AttributeName: humRel
          AttributeType: S      
        - AttributeName: velViento
          AttributeType: S
        - AttributeName: nubosTotal
          AttributeType: S 
        - AttributeName: precip
          AttributeType: S 
        - AttributeName: frecDiasPrecipSuperior
          AttributeType: S            
      KeySchema:
        - AttributeName: uuid
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1      
      GlobalSecondaryIndexes:
        - IndexName: estacion
          KeySchema:
            - AttributeName: estacion
              KeyType: HASH    
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1 
        - IndexName: temp
          KeySchema: 
            - AttributeName: temp
              KeyType: HASH    
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1 
        - IndexName: tempMax
          KeySchema:
            - AttributeName: tempMax
              KeyType: HASH    
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1         
        - IndexName: tempMin
          KeySchema:
            - AttributeName: tempMin
              KeyType: HASH    
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1  
        - IndexName: humRel
          KeySchema:
            - AttributeName: humRel
              KeyType: HASH    
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
        - IndexName: velViento
          KeySchema:
            - AttributeName: velViento
              KeyType: HASH    
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1 
        - IndexName: nubosTotal
          KeySchema:
            - AttributeName: nubosTotal
              KeyType: HASH    
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1    
        - IndexName: precip
          KeySchema:
            - AttributeName: precip
              KeyType: HASH    
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1 
        - IndexName: frecDiasPrecipSuperior
          KeySchema:
            - AttributeName: frecDiasPrecipSuperior
              KeyType: HASH    
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1              


                                    
    